/* This file was generated by plugin 'Nordic Semiconductor nRF5x v.1.2.2' (BDS version 1.0.2116.0) */

#include "ble_ods.h"
#include <string.h>
#include "nordic_common.h"
#include "ble_srv_common.h"
#include "app_util.h"
#include "app_util_bds.h"

#define OPCODE_LENGTH 1 /**< Length of opcode inside ODER ID packet. */
#define HANDLE_LENGTH 2 /**< Length of handle inside ODER ID packet. */

/* TODO Consider changing the max values if encoded data for characteristic/descriptor is fixed length */ 
#define MAX_ODER_ID_BASIS_LEN (BLE_L2CAP_MTU_DEF - OPCODE_LENGTH - HANDLE_LENGTH) /**< Maximum size of a transmitted Oder Id Basis. */ 

/**@brief Function for encoding Oder Id Basis.
 *
 * @param[in]   p_oder_id_basis              Oder Id Basis characteristic structure to be encoded.
 * @param[out]  p_encoded_buffer   Buffer where the encoded data will be written.
 *
 * @return      Size of encoded data.
 */
static uint8_t oder_id_basis_encode(ble_oder_id_oder_id_basis_t * p_oder_id_basis, uint8_t * encoded_buffer)
{
    uint8_t len = 0; 
    len += bds_uint8_array_encode(&p_oder_id_basis->data, &encoded_buffer[len]); 
    return len;
}

/**@brief Function for decoding Oder Id Basis.
 *
 * @param[in]   data_len              Length of the field to be decoded.
 * @param[in]   p_data                Buffer where the encoded data is stored.
 * @param[out]  p_write_val           Decoded data.
 *
 * @return      Length of the decoded field.
 */
static uint8_t oder_id_basis_decode(uint8_t data_len, uint8_t * p_data, ble_oder_id_oder_id_basis_t * p_write_val)
{
    uint8_t pos = 0;
    pos += bds_uint8_array_decode((data_len-pos), &p_data[pos], &p_write_val->data); 

    return pos;
} 

/**@brief Function for handling the Connect event.
 *
 * @param[in]   p_oder_id       ODER ID Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_connect(ble_oder_id_t * p_oder_id, ble_evt_t * p_ble_evt)
{
    p_oder_id->conn_handle = p_ble_evt->evt.gap_evt.conn_handle;
}

/**@brief Function for handling the Disconnect event.
 *
 * @param[in]   p_oder_id       ODER ID Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_disconnect(ble_oder_id_t * p_oder_id, ble_evt_t * p_ble_evt)
{
    UNUSED_PARAMETER(p_ble_evt);
    p_oder_id->conn_handle = BLE_CONN_HANDLE_INVALID;
}

/**@brief Function for handling the Write event.
 *
 * @param[in]   p_oder_id       ODER ID Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
static void on_write(ble_oder_id_t * p_oder_id, ble_gatts_evt_write_t * p_ble_evt)
{
    
    if(p_ble_evt->handle == p_oder_id->oder_id_basis_handles.cccd_handle)
    {
        if(p_oder_id->evt_handler != NULL)
        {
            ble_oder_id_evt_t evt;
            evt.evt_type = BLE_ODER_ID_ODER_ID_BASIS_EVT_CCCD_WRITE;
            bds_uint16_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.cccd_value);
            p_oder_id->evt_handler(p_oder_id, &evt);
        }
    } 
    if(p_ble_evt->handle == p_oder_id->oder_id_basis_handles.value_handle)
    {
        if(p_oder_id->evt_handler != NULL)
        {
            ble_oder_id_evt_t evt;
            evt.evt_type = BLE_ODER_ID_ODER_ID_BASIS_EVT_WRITE;
            oder_id_basis_decode(p_ble_evt->len, p_ble_evt->data, &evt.params.oder_id_basis);
            p_oder_id->evt_handler(p_oder_id, &evt);
        }
    }
}

/**@brief Authorize WRITE request event handler.
 *
 * @details Handles WRITE events from the BLE stack.
 *
 * @param[in]   p_sc_ctrlpt  SC Ctrlpt structure.
 * @param[in]   p_gatts_evt  GATTS Event received from the BLE stack.
 *
 */
static void on_rw_authorize_request(ble_oder_id_t * p_oder_id, ble_gatts_evt_t * p_gatts_evt)
{
    ble_gatts_evt_rw_authorize_request_t * p_auth_req = &p_gatts_evt->params.authorize_request;
    if (p_auth_req->type == BLE_GATTS_AUTHORIZE_TYPE_WRITE)
    {
        if (   (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_PREP_WRITE_REQ)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_NOW)
            && (p_gatts_evt->params.authorize_request.request.write.op
                != BLE_GATTS_OP_EXEC_WRITE_REQ_CANCEL)
           )
        {
        
        }
    }
}

/**@brief Function for handling BLE events.
 *
 * @param[in]   p_oder_id       ODER ID Service structure.
 * @param[in]   p_ble_evt   Event received from the BLE stack.
 */
void ble_oder_id_on_ble_evt(ble_oder_id_t * p_oder_id, ble_evt_t * p_ble_evt)
{
    switch (p_ble_evt->header.evt_id)
    {
        case BLE_GAP_EVT_CONNECTED:
            on_connect(p_oder_id, p_ble_evt);
            break;
        case BLE_GAP_EVT_DISCONNECTED:
            on_disconnect(p_oder_id, p_ble_evt);
            break;
        case BLE_GATTS_EVT_WRITE:
            on_write(p_oder_id, &p_ble_evt->evt.gatts_evt.params.write);
            break;
         case BLE_GATTS_EVT_RW_AUTHORIZE_REQUEST:
            on_rw_authorize_request(p_oder_id, &p_ble_evt->evt.gatts_evt);
            break;
        default:
            //No implementation needed.
            break;
    }
}

/**@brief Function for initializing the ODER ID. */
uint32_t ble_oder_id_init(ble_oder_id_t * p_oder_id, const ble_oder_id_init_t * p_oder_id_init)
{
    uint32_t err_code;
    ble_uuid_t ble_uuid;

    // Initialize service structure
    p_oder_id->evt_handler = p_oder_id_init->evt_handler;
    p_oder_id->conn_handle = BLE_CONN_HANDLE_INVALID;
    
    // Add a custom base UUID.
    ble_uuid128_t bds_base_uuid = {{0x0E, 0x94, 0x1B, 0x13, 0xFC, 0xC3, 0x5A, 0x9F, 0xA4, 0x4C, 0x5D, 0xFA, 0x00, 0x00, 0x71, 0x48}};
    uint8_t       uuid_type;
    err_code = sd_ble_uuid_vs_add(&bds_base_uuid, &uuid_type);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    }
    ble_uuid.type = uuid_type;
    ble_uuid.uuid = 0xE1E6;
        
    // Add service
    err_code = sd_ble_gatts_service_add(BLE_GATTS_SRVC_TYPE_PRIMARY, &ble_uuid, &p_oder_id->service_handle);
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    // Add Oder Id Basis characteristic
    ble_oder_id_oder_id_basis_t oder_id_basis_initial_value = p_oder_id_init->ble_oder_id_oder_id_basis_initial_value; 

    uint8_t oder_id_basis_encoded_value[MAX_ODER_ID_BASIS_LEN];
    ble_add_char_params_t add_oder_id_basis_params;
    memset(&add_oder_id_basis_params, 0, sizeof(add_oder_id_basis_params));
    
    add_oder_id_basis_params.uuid                = 0x8070;
    add_oder_id_basis_params.uuid_type           = ble_uuid.type; 
    add_oder_id_basis_params.max_len             = MAX_ODER_ID_BASIS_LEN;
    add_oder_id_basis_params.init_len            = oder_id_basis_encode(&oder_id_basis_initial_value, oder_id_basis_encoded_value);
    add_oder_id_basis_params.p_init_value        = oder_id_basis_encoded_value; 
    add_oder_id_basis_params.char_props.notify   = 1; 
    add_oder_id_basis_params.char_props.read     = 1; 
    add_oder_id_basis_params.read_access         = SEC_OPEN; 
    add_oder_id_basis_params.char_props.write_wo_resp    = 1; 
    add_oder_id_basis_params.write_access        = SEC_OPEN; 
    add_oder_id_basis_params.cccd_write_access   = SEC_OPEN;
    // 1 for variable length and 0 for fixed length.
    add_oder_id_basis_params.is_var_len          = 1; 

    err_code = characteristic_add(p_oder_id->service_handle, &add_oder_id_basis_params, &(p_oder_id->oder_id_basis_handles));
    if (err_code != NRF_SUCCESS)
    {
        return err_code;
    } 

    return NRF_SUCCESS;
}

/**@brief Function for setting the Oder Id Basis. */
uint32_t ble_oder_id_oder_id_basis_set(ble_oder_id_t * p_oder_id, ble_oder_id_oder_id_basis_t * p_oder_id_basis)
{
    ble_gatts_value_t gatts_value;
    uint8_t encoded_value[MAX_ODER_ID_BASIS_LEN];

    // Initialize value struct.
    memset(&gatts_value, 0, sizeof(gatts_value));

    gatts_value.len     = oder_id_basis_encode(p_oder_id_basis, encoded_value);
    gatts_value.offset  = 0;
    gatts_value.p_value = encoded_value;

    return sd_ble_gatts_value_set(p_oder_id->conn_handle, p_oder_id->oder_id_basis_handles.value_handle, &gatts_value);
}

/**@brief Function for sending the Oder Id Basis. */
uint32_t ble_oder_id_oder_id_basis_send(ble_oder_id_t * p_oder_id, ble_oder_id_oder_id_basis_t * p_oder_id_basis)
{
    uint32_t err_code = NRF_SUCCESS;

    if (p_oder_id->conn_handle != BLE_CONN_HANDLE_INVALID)
    {
        ble_gatts_hvx_params_t hvx_params;
        uint8_t encoded_value[MAX_ODER_ID_BASIS_LEN];
        uint16_t hvx_len;

        // Initialize value struct.
        memset(&hvx_params, 0, sizeof(hvx_params));

        hvx_len           = oder_id_basis_encode(p_oder_id_basis, encoded_value);
        hvx_params.handle = p_oder_id->oder_id_basis_handles.value_handle;
        hvx_params.type   = BLE_GATT_HVX_NOTIFICATION;
        hvx_params.p_len  = &hvx_len;
        hvx_params.offset = 0;
        hvx_params.p_data = encoded_value;

        err_code = sd_ble_gatts_hvx(p_oder_id->conn_handle, &hvx_params);
    }
    else
    {
        err_code = NRF_ERROR_INVALID_STATE;
    }

    return err_code;
}

